### ISSUE TITLE
handleLiveChat is not defined

### ISSUE THREAD

**Issue by lilith** [0xreeko/gpt2markdown#13]
```
Uncaught ReferenceError: handleLiveChat is not defined
    at HTMLButtonElement.handleClick (script.js:30:5)
script.js:30 Uncaught ReferenceError: handleLiveChat is not defined
    at HTMLButtonElement.handleClick (script.js:30:5)
handleClick @ script.js:30
```

**Comment by phugadev** [comment]
thanks for opening the issue! I've implemented the needed changes and have submitted it to the Chrome web store - it'll be live shortly once they approve👍
